[project]
name = "customer-support-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jaskaranvirk01", email = "virk7184@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "langchain-mistralai>=1.1.6",
    "langchain-openai>=1.6.0",
    "langgraph>=1.2.11",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
customer-support-ai = "customer_support_ai:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
